# Generated by Django 5.0.1 on 2024-01-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0002_reservation_table_delete_evenement_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nom',
            field=models.CharField(default='NoName', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_info.table'),
        ),
    ]
